# Generated by Django 2.0.7 on 2018-07-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its_quote_dash', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='its_quote_dash.User'),
        ),
    ]
