# Generated by Django 2.0.7 on 2018-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_quote_dash', '0003_auto_20180724_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
