# Generated by Django 2.0.7 on 2018-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_quote_dash', '0004_quote_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
